swagger: '2.0'
info:
  title: review
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /review:
    post:
      summary: ''
      operationId: post-review
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              success:
                type: string
              message:
                type: string
      description: Create review
      parameters:
        - in: body
          name: body
          schema:
            $ref: ../models/review.yaml
definitions: {}
