swagger: '2.0'
info:
  title: review
  version: '1.0'
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
  description: Post review with sentiment
host: c620371127fa.ngrok.io
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /review:
    post:
      summary: ''
      operationId: post-review
      responses:
        '200':
          description: OK
          schema:
            $ref: ../models/response.yaml
      description: Create review
      parameters:
        - in: body
          name: body
          schema:
            $ref: ../models/review.yaml
      tags:
        - Review
      security:
        - apikey: []
definitions: {}
tags:
  - name: Review
basePath: /api
securityDefinitions:
  apikey:
    name: l87iUwdO54tIelwH+jcc0vi9gLoYkCha
    type: apiKey
    in: header
security:
  - apikey: []
