swagger: '2.0'
info:
  title: review
  version: '1.0'
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
  description: Post review with sentiment
host: a4f11e8d58f0edeac2c5b589b508f5b2d8945234.cloudapp-enterprise.appcelerator.com
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /review:
    post:
      summary: ''
      operationId: post-review
      responses:
        '200':
          description: OK
          schema:
            $ref: ../models/response.yaml
      description: Create review
      parameters:
        - in: body
          name: body
          schema:
            $ref: ../models/review.yaml
      tags:
        - Review
    parameters: []
definitions: {}
tags:
  - name: Review
securityDefinitions:
  apikey:
    name: apikey
    type: apiKey
    in: header
    description: ''
security:
  - apikey: []
basePath: /api
