swagger: '2.0'
info:
  title: review
  version: '1.0'
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
  description: Post review with sentiment
host: 'localhost:8080'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /api/review:
    post:
      summary: ''
      operationId: post-review
      responses:
        '200':
          description: OK
          schema:
            $ref: ../models/response.yaml
      description: Create review
      parameters:
        - in: body
          name: body
          schema:
            $ref: ../models/review.yaml
        - type: string
          in: header
      tags:
        - Review
    parameters: []
definitions: {}
tags:
  - name: Review
securityDefinitions:
  apikey:
    name: apikey
    type: apiKey
    in: header
    description: ''
security:
  - apikey: []
